#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/../.."

if ./run_tests.sh > /dev/null 2>&1; then
    git add -A
    git commit -m "Added tests"
    exit 0
else
    git reset --hard
    exit 1
fi
